//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sxva_saqartvelo_back_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancer_Skill
    {
        public int ID { get; set; }
        public int SkillID { get; set; }
        public int FreelancerID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
