//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sxva_saqartvelo_back_end.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue()
        {
            this.Issue_Status = new HashSet<Issue_Status>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "ჩაწერეთ ამოცანის სახელი")]
        public string Name { get; set; }
        [Required(ErrorMessage = "ჩაწერეთ პროექტის აღწერა")]
        public string Body { get; set; }
        public int AdminID { get; set; }
        public bool isCompleted { get; set; }
        public int ProjectID { get; set; }
        [Required(ErrorMessage = "აირჩიეთ თარიღი შესასრულებლად")]
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DueDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Status> Issue_Status { get; set; }
    }
}
