//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sxva_saqartvelo_back_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Status
    {
        public int ID { get; set; }
        public int IssueID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Status Status { get; set; }
    }
}
